[package]
name = "draw_triangles"
version = "0.1.0"
authors = ["Simon Heath <icefoxen@gmail.com>"]

[dependencies]
delaunator = {path="../../"}
# ggez = "0.5"
ggez = {git = "https://github.com/ggez/ggez.git", branch="devel"}
rand = "0.5"